### ISSUE TITLE
扮演群友功能无法禁言

### ISSUE THREAD

**Issue by NekoMirra** [ChatLunaLab/chatluna-character#11]
如题，禁言关键词发送了也没用，而且时不时会突然重复好多遍自我介绍，有没有什么新鲜事什么的

**Comment by dingyi222666** [comment]
请提供详细的 log，图片等

**Comment by NekoMirra** [comment]
![PixPin_2024-12-09_21-07-44](https://github.com/user-attachments/assets/a6ff98d4-218f-427f-bc23-7e89e5e41344)
log一切正常，但会突然开始重复好几遍自我介绍

**Comment by dingyi222666** [comment]
预设可以多改改，伪装插件的精髓都在预设上

**Comment by dingyi222666** [comment]
伪装没有长期记忆模块，聊天记录也不会长期存储

语句分割无法设置规则

**Comment by NekoMirra** [comment]
> 伪装没有长期记忆模块，聊天记录也不会长期存储
> 
> 语句分割无法设置规则

考虑过接入到chatluna的那个自带的数据库功能嘛
语句分割目前确实是太碎了

**Comment by dingyi222666** [comment]
没有考虑

**Comment by dingyi222666** [comment]
如果需要保留历史聊天记录等，建议使用主插件

**Comment by NekoMirra** [comment]
✖
