### ISSUE TITLE
在读取带@的回复类型消息时出现bug

### ISSUE THREAD

**Issue by Ocetars** [ChatLunaLab/chatluna-character#5]
错误信息如图![Screenshot_2024-04-28-10-32-36-268_com.tencent.mobileqq.png](https://github.com/ChatLunaLab/chatluna-character/assets/74854972/cd5076df-1f58-4722-9e62-2411681c6334)

![Screenshot_2024-04-28-10-32-55-206_youqu.android.todesk.png](https://github.com/ChatLunaLab/chatluna-character/assets/74854972/83f21290-bc7d-4391-9b04-64162cbf8a25)

出现此错误后程序无法在当前群聊中继续读取新消息，在其它订阅群聊中表现为正常

**Comment by dingyi222666** [comment]
看一下修复了没,我更新了

**Comment by Ocetars** [comment]
> 看一下修复了没,我更新了

更新解决了，辛苦作者✨
