### ISSUE TITLE
在将chatluna-character克隆到本地koishi build时出现error TS2322: Type 'BaseMessageChunk' is not assignable to type 'BaseMessage'

### ISSUE THREAD

**Issue by intling-luo** [ChatLunaLab/chatluna-character#6]
为了避免环境因素,我重新部署了koishi并更新了所有依赖项,再次克隆build时错误复现

错误日志:
`dtsc: /external/chatluna/packages/chatglm-adapter/lib/index.d.ts
dtsc: /external/chatluna/packages/bard-adapter/lib/index.d.ts
dtsc: /external/chatluna/packages/azure-openai-adapter/lib/index.d.ts
src/plugins/chat.ts:140:17 - error TS2322: Type 'BaseMessageChunk' is not assignable to type 'BaseMessage'.
  The types returned by '_getType()' are incompatible between these types.
    Type 'import("D:/koishi/dev/koishi-app/node_modules/@langchain/core/dist/messages/base").MessageType' is not assignable to type 'import("D:/koishi/dev/koishi-app/external/chatluna-character/node_modules/@langchain/core/dist/messages/base").MessageType'.
      Type '"remove"' is not assignable to type 'MessageType'.

140                 responseMessage = await model.invoke(completionMessages)
                    ~~~~~~~~~~~~~~~

src/plugins/chat.ts:140:54 - error TS2345: Argument of type 'BaseMessage[]' is not assignable to parameter of type 'BaseLanguageModelInput'.
  Type 'BaseMessage[]' is not assignable to type 'BaseMessageLike[]'.
    Type 'BaseMessage' is not assignable to type 'BaseMessageLike'.
      Type 'BaseMessage' is not assignable to type '{ type: MessageType | "user" | "assistant" | "placeholder"; } & BaseMessageFields & Record<string, unknown>'.
        Property 'type' is missing in type 'BaseMessage' but required in type '{ type: MessageType | "user" | "assistant" | "placeholder"; }'.
        Property 'type' is missing in type 'BaseMessage' but required in type '{ type: MessageType | "user" | "assistant" | "placeholder"; }'.


140                 responseMessage = await model.invoke(completionMessages)
140                 responseMessage = await model.invoke(completionMessages)
                                                         ~~~~~~~~~~~~~~~~~~
                                                         ~~~~~~~~~~~~~~~~~~

  ../../node_modules/@langchain/core/dist/messages/base.d.ts:157:5
    157     type: MessageType | "user" | "assistant" | "placeholder";
    157     type: MessageType | "user" | "assistant" | "placeholder";
            ~~~~
    'type' is declared here.


Found 2 errors in the same file, starting at: src/plugins/chat.ts:140`

**Comment by dingyi222666** [comment]
看起来是依赖版本不一致导致的，删除 yarn.lock 之后重新运行 harn

**Comment by intling-luo** [comment]
> 看起来是依赖版本不一致导致的，删除yarn.lock然后重新运行yarn

删除yarn.lock后build运行出现:
`Internal Error: koishi-app@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Xx.getCandidates (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:205:8149)
    at Dd.getCandidates (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:141:1311)
    at D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:210:8409
    at Ky (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:140:53916)
    at Fe (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:210:8389)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async Uc (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:140:53244)
    at async D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:210:9140
    at async Qi.startProgressPromise (D:\koishi\dev\koishi-app\.yarn\releases\yarn-4.1.1.cjs:140:137284)`
    
于是我yarn install了,然后再次build,出现了和最开始一样的错误
    `error TS2322: Type 'BaseMessageChunk' is not assignable to type 'BaseMessage`

**Comment by dingyi222666** [comment]
我已经将 chatluna 相关项目所使用的依赖全部升级到最新版本。将 chatluna 相关仓库  `git pull --rebase` 跟随上游后，做以下操作。

1. 删除 `yarn.lock`。
2. 在模版项目主目录运行 `yarn` 操作（只需要执行 yarn）
3. 在模版项目主目录下运行 `yarn workspace @root/chatluna-koishi install`
4. 回到模版项目主目录，重新运行 `yarn install`
5. 在模版项目主目录下运行 `yarn workspace @root/chatluna-koishi build`
6. 然后就可以单独构建 `chatluna-character`，我一般在模版项目主目录下运行 `yarn build chatluna-character`，其中 `chatluna-character` 为存放伪装项目的文件夹名称。

## 注意的事项

1. `chatluna` 主项目（https://github.com/ChatLunaLab/chatluna）使用了一些脚本在 `build` 时运行，不适用于在模版项目主目录下直接运行 `yarn build`。
2. 如果只是单独修改 `chatluna-character`，无需在克隆 chatluna 主项目，只需要确保模版项目下安装了最新的 `koshi-plugin-chatluna` 即可。
3. 关于依赖冲突：可以使用 `yarn why <package-name>` 查看该依赖被那些本地项目引用了，以及它的版本。如果遇到了 Type 'xxx' is not assignable to type 'xx'，需要手动排除是那个依赖的问题。（大部分情况下删除 yarn.lock 重新 install 可以解决）
